#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:          backoffice_api
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the backoffice api
# Description:       starts uwsgi backoffice api using start-stop-daemon
### END INIT INFO
set -e


DAEMON=/var/buildbot/workers/backoffice_api/venv/bin/uwsgi
CHDIR=/var/buildbot/workers/backoffice_api/BackofficeApi/build/
RUN_DIR=/var/run
LOG_DIR=/var/log
NAME=backoffice_api
DESC="Backoffice API"
# OWNER=www-data
# GROUP=www-data

PROCESSES=5
LISTEN=50
HARAKIRI=120
STATS_PORT=6666

[[ -x $DAEMON ]] || echo "Daemon does not exist" || exit 0
[[ -d $RUN_DIR ]] || mkdir $RUN_DIR && chown $OWNER:$GROUP $RUN_DIR
[[ -d $LOG_DIR ]] || mkdir $LOG_DIR && chown $OWNER:$GROUP $LOG_DIR

do_pid_check()
{
    local PIDFILE=$1
    [[ -f $PIDFILE ]] || return 0
    local PID=$(cat $PIDFILE)
    for p in $(pgrep $NAME); do
        [[ $p == $PID ]] && return 1
    done
    return 0
}


do_start()
{
    local PIDFILE=$RUN_DIR/$NAME.pid
    local START_OPTS="                      \
        --master                            \
        --socket 0.0.0.0:5541               \
        --chdir $CHDIR                      \
        -w backoffice.wsgi:application      \
        --processes $PROCESSES              \
        --enable-threads                    \
        --listen $LISTEN                    \
        --stats :$STATS_PORT                \
        --harakiri $HARAKIRI                \
        --pidfile $PIDFILE                  \
        --daemonize $LOG_DIR/$NAME.log"
    if do_pid_check $PIDFILE; then
        $DAEMON $START_OPTS
    else
        echo "Already running!"
    fi
}

send_sig()
{
    local PIDFILE=$RUN_DIR/$NAME.pid
    set +e
    [[ -f $PIDFILE ]] && kill $1 $(cat $PIDFILE) > /dev/null 2>&1
    set -e
}

wait_and_clean_pidfile()
{
    local PIDFILE=$RUN_DIR/$NAME.pid
    until do_pid_check $PIDFILE; do
        echo -n "";
    done
    rm -f $PIDFILE
}

do_stop()
{
    send_sig -3
    wait_and_clean_pidfile
}

do_reload()
{
    send_sig -1
}

do_force_reload()
{
    send_sig -15
}

get_status()
{
    send_sig -10
}

case "$1" in
    start)
        echo "Starting $DESC: "
        do_start
        echo "$NAME."
        ;;
    stop)
        echo -n "Stopping $DESC: "
        do_stop
        echo "$NAME."
        ;;
    reload)
        echo -n "Reloading $DESC: "
        do_reload
        echo "$NAME."
        ;;
    force-reload)
        echo -n "Force-reloading $DESC: "
        do_force_reload
        echo "$NAME."
       ;;
    restart)
        echo  "Restarting $DESC: "
        do_stop
        sleep 1
        do_start
        echo "$NAME."
        ;;
    status)
        get_status
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|reload|force-reload|status}">&2
        exit 1
        ;;
esac
exit 0